COMP2084_Project_Eventour/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP2084_Project_Eventour.Data;
using COMP2084_Project_Eventour.Models;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using System.Data;
using System.Drawing;
using Microsoft.AspNetCore.Authorization;

namespace COMP2084_Project_Eventour.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }


        [AllowAnonymous]
        // GET: Events
        public async Task<IActionResult> Index()
        {
            //var applicationDbContext = _context.Events.Include(
            //    @ => @.EventDetail).Include(@ => @.User
            //    );


            //var applicationDbContext = from e in _context.Events join ed in _context.EventDetails on e.EventDetailId equals ed.EventDetailId join ev in _context.EventVenues on ed.EventVenueId equals ev.EventVenueId select new
            //{
            //    Title = e.Title,
            //    Description = e.Description,
            //    Address = ev.Address,
            //    CreatedOn = e.createdOn,

            //};

            // This works and joins the tables.
            var applicationDbContext = _context.Events
                .Include(x => x.User)
                .Include(x => x.EventDetail)
                .ThenInclude(x => x.Category)
                .Include(x => x.EventDetail)
                .ThenInclude(x => x.EventVenue);
                

            return View(await applicationDbContext.ToListAsync());
        }


        [AllowAnonymous]
        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
               .Include(item => item.EventDetail)
               .ThenInclude(item => item.EventVenue)
               .Include(item => item.EventDetail)
               .ThenInclude(item => item.Category)
               .Include(item => item.User)
               .FirstOrDefaultAsync(m => m.EventId == id);

           
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
           ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
           //public List<EventVenue> EventTypes { get; set; } = new List<EventVenue>
           // {
           // };

            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(
            "EventId,Title, Description,EventDetailId, UserId, EventDetail.Photo"
            )] Event @event, IFormFile? Photo)
        {

            if (ModelState.IsValid)
            {
                try
                {
                
                    // Create the Venue into the database and return the ID.
                    int eventType = int.Parse(HttpContext.Request.Form["EventDetail.EventVenue.Type"]);
                    string Address = HttpContext.Request.Form["EventDetail.EventVenue.Address"];
                    string City = HttpContext.Request.Form["EventDetail.EventVenue.City"];
                    string State = HttpContext.Request.Form["EventDetail.EventVenue.State"];
                    string Country = HttpContext.Request.Form["EventDetail.EventVenue.Country"];
                    string Zip = HttpContext.Request.Form["EventDetail.EventVenue.Zip"];

                    // need to get event detail id first then add to event.
                    var EventVenueId = new EventVenuesController(_context).CreateVenue(eventType,Address, City, State, Country, Zip);

                    // Create the Details into the database and return the ID.
                    double Price = Double.Parse(HttpContext.Request.Form["EventDetail.Price"]);
                    DateTime StartDate = DateTime.Parse(HttpContext.Request.Form["EventDetail.StartDate"]);
                    DateTime EndDate = DateTime.Parse(HttpContext.Request.Form["EventDetail.EndDate"]);

                
                    int CategoryId = int.Parse(HttpContext.Request.Form["EventDetail.CategoryId"]);

                    // Builds the event details and returns it ID.
                    var EventDetailId = new EventDetailsController(_context).CreateDetail(Price, StartDate, EndDate, CategoryId, EventVenueId);

                    // Need to get the photo and save it.
                    string? PhotoName = "placeholder.png";

                    if (Photo != null)
                    {
                        var fileName = UploadPhoto(Photo);
                        PhotoName = fileName;
                    }

                    @event.EventDetailId = EventDetailId;
                    @event.UserId = 1;
                    @event.createdOn = DateTime.Now;
                    @event.Photo = PhotoName;

                    _context.Add(@event);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }  

            ViewData["EventDetailId"] = new SelectList(_context.EventDetails, "EventDetailId", "EventDetailId", @event.EventDetailId);
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", @event.UserId);
            return View(@event);
        }

        
        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            @event.EventDetail = await _context.EventDetails.FindAsync(@event.EventDetailId);
            @event.EventDetail.EventVenue = await _context.EventVenues.FindAsync(@event.EventDetail.EventVenueId);

            if (@event == null)
            {
                return NotFound();
            }


            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");


            //ViewData["EventDetailId"] = new SelectList(_context.EventDetails, "EventDetailId", "EventDetailId", @event.EventDetailId);
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", @event.UserId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,Title,Description,EventDetailId,UserId")] Event @event, IFormFile? Photo, string? CurrentPhoto)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Create instance of the object.
                    EventDetail eventDetail = new EventDetail();
                    EventVenue eventVenue = new EventVenue();

                    //Get the current state from the database.
                    eventDetail = _context.EventDetails.Find(@event.EventDetailId);
                    eventVenue = _context.EventVenues.Find(eventDetail.EventVenueId);
                      

                    // Get the updated form info.
                    int eventType = int.Parse(HttpContext.Request.Form["EventDetail.EventVenue.Type"]);
                    string Address = HttpContext.Request.Form["EventDetail.EventVenue.Address"];
                    string City = HttpContext.Request.Form["EventDetail.EventVenue.City"];
                    string State = HttpContext.Request.Form["EventDetail.EventVenue.State"];
                    string Country = HttpContext.Request.Form["EventDetail.EventVenue.Country"];
                    string Zip = HttpContext.Request.Form["EventDetail.EventVenue.Zip"];

                    // Create the Details into the database and return the ID.
                    double Price = Double.Parse(HttpContext.Request.Form["EventDetail.Price"]);
                    DateTime StartDate = DateTime.Parse(HttpContext.Request.Form["EventDetail.StartDate"]);
                    DateTime EndDate = DateTime.Parse(HttpContext.Request.Form["EventDetail.EndDate"]);

                    int CategoryId = int.Parse(HttpContext.Request.Form["EventDetail.CategoryId"]);


                    // Update the model variables.
                    eventVenue.Type = (EventVenue.EventType)eventType;
                    eventVenue.Address = Address;
                    eventVenue.City = City;
                    eventVenue.State = State;
                    eventVenue.Country = Country;
                    eventVenue.Zip = Zip;

                    eventDetail.CategoryId = CategoryId;
                    eventDetail.Price = Price;
                    eventDetail.StartDate = StartDate;
                    eventDetail.EndDate = EndDate;

COMP2084_Project_Eventour/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using COMP2084_Project_Eventour.Models;
using Microsoft.EntityFrameworkCore;
using COMP2084_Project_Eventour.Data;

namespace COMP2084_Project_Eventour.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    private readonly ApplicationDbContext _context;

    public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
    {
        _context = context;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
       
        var applicationDbContext = _context.Events
                .Include(x => x.User)
                .Include(x => x.EventDetail)
                .ThenInclude(x => x.Category)
                .Include(x => x.EventDetail)
                .ThenInclude(x => x.EventVenue);


        return View(await applicationDbContext.ToListAsync());
        //return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

COMP2084_Project_Eventour/Views/Home/Index.cshtml
@model List<COMP2084_Project_Eventour.Models.Event>

@{
    ViewData["Title"] = "Events Dashboard";
}

<div class="container">

    @*Dummy Categories*@
    <div class="container">
        <h4>Browse By Categories</h4>

        <div class="container mb-3 mt-3">
            <div class="row">
                <div class="col category-cols">
                    Construction
                </div>
                <div class="col category-cols">
                    Technology
                </div>
                <div class="col category-cols">
                    Health
                </div>
                <div class="col category-cols">
                    Performing & Visual Arts
                </div>
            </div>

            <div class="row">
                <div class="col category-cols">
                    Music
                </div>
                <div class="col category-cols">
                    Travel & Outdoor
                </div>
                <div class="col category-cols">
                    Food & Drink
                </div>
                <div class="col category-cols">
                    Business
                </div>
            </div>
        </div>

    </div>


    <div class="text-center">
        <h3 class="display-6">Popular Events</h3>
        <p>Exploring your interest by controlling what you want to see.</p>
    </div>

    <div class="container mt-3 mb-3">
        <div class="row">
            @if (@Model.Count() < 1)
            {
                <div class="container col-12">
                    <h4>There are currently no events to show. Please create a new event.</h4>
                </div>
            }
            else
            {
                @foreach (var item in Model)
                {
                      
                    <div class="col-4 mb-3 mt-3">
                        <div class="container">
                            <div class="card" style="width: 18rem;">
                                <img src="assets/images/events/@Html.DisplayFor(modelItem => item.Photo)" class="card-img-top" alt="@Html.DisplayFor(modelItem => item.Title)">
                                <div class="card-body">
                                    <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Title)</h5>
                                    <p class="card-text">@Html.DisplayFor(modelItem => item.Description).</p>
                                </div>

                                <ul class="list-group list-group-flush card-body-group">
                                    <li class="list-group-item card-body-group">
                                        Category
                                        <span class="badge rounded-pill bg-light text-dark" style="border:3px solid @Html.DisplayFor(modelItem => item.EventDetail.Category.Color); ">@Html.DisplayFor(modelItem => item.EventDetail.Category.Name)</span> -
                                        <span class="badge bg-dark rounded-pill">
                                            @Html.DisplayFor(modelItem => item.EventDetail.EventVenue.Type)
                                        </span>
                                    </li>
                                    <li class="list-group-item card-body-group">
                                        <span>
                                            Price:
                                        </span>
                                        <span>
                                            @Html.DisplayFor(modelItem => item.EventDetail.Price)
                                        </span>
                                    </li>
                                    <li class="list-group-item card-body-group">
                                        <div class="text-start">
                                            <span>
                                                Start:
                                            </span>
                                            <span class="event-card-time-font">
                                                @Html.DisplayFor(modelItem => item.EventDetail.StartDate)
                                            </span>
                                        </div>
                                        <div class="text-start">
                                            <span>
                                                End:
                                            </span>
                                            <span class="event-card-time-font">
                                                @Html.DisplayFor(modelItem => item.EventDetail.EndDate)
                                            </span>
                                        </div>
                                    </li>
                                </ul>
                                <div class="card-footer">
                                    <div class="row text-center">
                                        <div class="col-12">
                                            <a asp-controller="Events" asp-action="Details" asp-route-id="@item.EventId" class="btn btn-success">Register</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>

</div>